name: housing
channels:
- conda-forge
- defaults
dependencies:
  - python=3.9
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - xgboost=2.1.1
  - numpy<2s
  - pip
  - pip:
      - fastapi==0.110.3
      - pydantic==2.12.3
      - uvicorn==0.30.6
      - requests==2.32.5
      - optuna==4.5.0